"""
LLM-as-a-Judge Evaluation Pipeline (Llama 3 70B via Groq)
-------------------------------------------------
This script evaluates the factuality of the previously selected centroids 
by using Llama 3 70B as a critical evaluator (Patronus AI / Lynx prompt).
It computes AUROC, AURC, and ECE based on the generated hallucination score.

Requirements:
- pip install groq
- Ensure your Groq API key is set: os.environ["GROQ_API_KEY"] = "gsk_..."
"""

import os
import json
import re
import pandas as pd
from tqdm import tqdm
from pathlib import Path
from groq import Groq

# Import existing evaluation logic
from calculate_eval_metrics import EvalMethods


# --- Path Management ---
PROJECT_ROOT = Path(__file__).resolve().parents[1]
STATS_DIR = PROJECT_ROOT / "outputs" / "stats"
os.makedirs(STATS_DIR, exist_ok=True)
# Ensure GROQ_API_KEY is defined in your environment variables
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

def get_llama_score(question, reference, response):
    """
    Sends a prompt to Llama 3 70B via Groq to evaluate hallucination probability.
    Returns a normalized score between 0.0 and 1.0.
    """
    prompt = f"""
    [INST] You are a critical factual evaluator.
    Compare the 'Model Response' against the 'Ground Truth Reference'.
    Assign a score from 0 to 10 based on the probability of hallucination.
    
    - 0: The response is perfectly factual and matches the reference.
    - 10: The response is a total hallucination or contradicts the reference.

    Output ONLY the integer score.

    Question: {question}
    Ground Truth Reference: {reference}
    Model Response: {response}
    [/INST]
    Score (0-10):"""

    try:
        chat_completion = client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            # Using the production-ready Llama 3 70B model on Groq
            model="llama3-70b-8192",
            temperature=0.0, # Determinstic output for evaluation
            max_tokens=10,   # We only need the score
        )
        
        content = chat_completion.choices[0].message.content.strip()
        
        # Robust extraction of the first integer found
        match = re.search(r'\d+', content)
        if match:
            score = int(match.group())
            return min(score / 10.0, 1.0)
        else:
            return 0.5 # Neutral fallback if no digit is found
    except Exception as e:
        print(f"Error calling Groq API: {e}")
        return 0.5

def evaluate_llm_judge_performance():
    """
    Loads centroid files, performs LLM-as-a-judge evaluation using Llama 3 70B,
    and generates evaluation metrics (AUROC, AURC, ECE).
    """
    
    # Find the centroid files generated by centroids_selection.py
    centroid_files = list(STATS_DIR.glob("*_centroid.json"))

    if not centroid_files:
        print(f"Error: No centroid files found in {STATS_DIR}. Please run centroids_selection.py first.")
        return

    for file_path in centroid_files:
        ds_name = file_path.stem.replace("_centroid", "")
        print(f"\n[Processing Dataset: {ds_name} with Llama 3 70B on Groq]")

        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        y_true = []      # Ground truth labels (is_hallucination)
        y_scores_j = []  # Judge scores (The risk metric)

        # Process samples one by one
        #for item in tqdm(data, desc=f"Judging {ds_name}"):
            #question = item.get('question', "N/A")
        for item in tqdm(data[:10], desc=f"Judging {ds_name} (Test 10 samples)"):
            question = item.get('question', "N/A")
            reference = item['ground_truth']
            response = item['selected_response']
            label = item['is_hallucination']

            # Call the LLM judge
            score = get_llama_score(question, reference, response)

            y_scores_j.append(score)
            y_true.append(label)

        # --- Metrics Calculation ---
        evaluator = EvalMethods(y_true, print_logs=True)
        
        # Method name for logging and file naming
        method_name = "llm_judge_groq"
        score_name = f"llama3_70b_{ds_name}"
        
        # Calculate AUROC, AURC, ECE and save plots
        evaluator.plot_roc(
            y_scores=y_scores_j, 
            name_method=method_name, 
            name_score=score_name
        )

        # Save specific CSV for this dataset
        output_csv = STATS_DIR / f"{ds_name}_llm_judge_metrics.csv"
        evaluator.save_eval_metrics(str(output_csv))
        
        print(f"Results for {ds_name} saved to {output_csv}")

if __name__ == "__main__":
    # Check if API Key is present
    if not os.environ.get("GROQ_API_KEY"):
        print("Error: GROQ_API_KEY not found in environment variables.")
    else:
        try:
            evaluate_llm_judge_performance()
            print(f"\nLLM-as-a-Judge Evaluation complete. Metrics and plots are in: {STATS_DIR}")
        except Exception as e:
            print(f"Pipeline failed: {e}")