"""
NLI Evaluation Pipeline (Centroid vs Ground Truth)
-------------------------------------------------
This script evaluates the factuality of the previously selected centroids 
by comparing them against the ground truth using NLI (DeBERTa-v3).
It computes AUROC, AURC, and ECE based on the Contradiction score.
"""

import os
import json
import torch
import pandas as pd
from tqdm import tqdm
from pathlib import Path
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# Import existing evaluation logic
from calculate_eval_metrics import EvalMethods

# --- Path Management ---
PROJECT_ROOT = Path(__file__).resolve().parents[1]
STATS_DIR = PROJECT_ROOT / "outputs" / "stats"
os.makedirs(STATS_DIR, exist_ok=True)

def evaluate_nli_performance():
    """
    Loads centroid files, calculates NLI contradiction scores against ground truth,
    and generates evaluation metrics (AUROC, AURC, ECE).
    """
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model_name = "cross-encoder/nli-deberta-v3-large"
    
    print(f"--- Loading NLI Model: {model_name} on {device} ---")
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(model_name).to(device)
    model.eval()

    # Find the centroid files generated by centroids_selection.py
    centroid_files = list(STATS_DIR.glob("*_centroid.json"))

    if not centroid_files:
        print(f"Error: No centroid files found in {STATS_DIR}. Please run centroids_selection.py first.")
        return

    for file_path in centroid_files:
        ds_name = file_path.stem.replace("_centroid", "")
        print(f"\n[Processing Dataset: {ds_name}]")

        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        y_true = []      # Manual labels (is_hallucination)
        y_scores_c = []  # Contradiction scores (The risk metric)

        # We process in batches for efficiency
        batch_size = 16
        for i in tqdm(range(0, len(data), batch_size), desc="Computing NLI Scores"):
            batch = data[i : i + batch_size]
            
            # Prepare pairs: (Selected Response, Ground Truth)
            # We want to see if the response contradicts the ground truth
            pairs = [(item['selected_response'], item['ground_truth']) for item in batch]
            labels = [item['is_hallucination'] for item in batch]

            inputs = tokenizer(pairs, padding=True, truncation=True, return_tensors="pt").to(device)

            with torch.no_grad():
                logits = model(**inputs).logits
                # cross-encoder/nli-deberta-v3-large mapping:
                # Index 0: Contradiction, Index 1: Neutral, Index 2: Entailment
                probs = torch.softmax(logits, dim=1)
                
                # We use Contradiction (Index 0) as our hallucination score
                contradiction_scores = probs[:, 0].cpu().tolist()

            y_scores_c.extend(contradiction_scores)
            y_true.extend(labels)

        # --- Metrics Calculation ---
        evaluator = EvalMethods(y_true, print_logs=True)
        
        # Compute and Plot
        method_name = "nli_eval"
        score_name = f"contradiction_{ds_name}"
        
        # This will calculate AUROC, AURC, ECE and save the plot
        evaluator.plot_roc(
            y_scores=y_scores_c, 
            name_method=method_name, 
            name_score=score_name
        )

        # Save specific CSV for this dataset
        output_csv = STATS_DIR / f"{ds_name}_nli_metrics.csv"
        evaluator.save_eval_metrics(str(output_csv))
        
        print(f"Results for {ds_name} saved to {output_csv}")

if __name__ == "__main__":
    try:
        evaluate_nli_performance()
        print(f"\nNLI Evaluation complete. Metrics and plots are in: {STATS_DIR}")
    except Exception as e:
        print(f"Pipeline failed: {e}")